#ifndef SPACESHOOTER_EVENT_H
#define SPACESHOOTER_EVENT_H

enum Event {
    PLAYER_BEAM_SHOOT,
    PLAYER_MISSILE_LAUNCHED,
    PLAYER_SQUARED_PROJECTILE_SHOOT,
    PLAYER_CIRCLE_PROJECTILE_SHOOT,
    PLAYER_MISSILE_EXPLODED,
    PLAYER_ITEM_UNEQUIPPED,
    PLAYER_DAMAGED,
    PLAYER_DIED,
    ENEMY_PROJECTILE_SHOOT,
    ENEMY_MISSILE_LAUNCHED,
    ENEMY_MISSILE_EXPLODED,
    ENEMY_SPARKLE_SPAWNED,
    MISSILE_ITEM_PICKED_UP,
    SQUARED_ITEM_PICKED_UP,
    CIRCLE_ITEM_PICKED_UP,
    CANDY_ENEMY_SPAWNED,
    KAMIKAZE_ENEMY_SPAWNED,
    SHELL_ENEMY_SPAWNED,
    PICKUP_ITEM_SPAWNED,
    ENEMY_KILLED,
    ENEMY_DIED,
    PICKUP_DIED,
    GAME_STARTED,
};
#endif //SPACESHOOTER_EVENT_H