#ifndef SPACESHOOTER_EVENT_H
#define SPACESHOOTER_EVENT_H

enum Event {
    PLAYER_BEAM_SHOOT,
    ENEMY_PROJECTILE_SHOOT,
    ENEMY_MISSILE_LAUNCHED,
    ENEMY_MISSILE_EXPLODED,
    ENEMY_SPARKLE_SPAWNED
};

#endif //SPACESHOOTER_EVENT_H