#ifndef SPACESHOOTER_EVENT_H
#define SPACESHOOTER_EVENT_H

enum Event {
    PLAYER_BEAM_SHOOT,
    PLAYER_MISSILE_LAUNCHED,
    PLAYER_MISSILE_EXPLODED,
    PLAYER_ITEM_UNEQUIPPED,
    ENEMY_PROJECTILE_SHOOT,
    ENEMY_MISSILE_LAUNCHED,
    ENEMY_MISSILE_EXPLODED,
    ENEMY_SPARKLE_SPAWNED,
    MISSILE_ITEM_PICKED_UP,
    SQUARED_ITEM_PICKED_UP,
    CIRCLE_ITEM_PICKED_UP,
    CANDY_ENEMY_SPAWNED,
    KAMIKAZE_ENEMY_SPAWNED,
    SHELL_ENEMY_SPAWNED,
    PICKUP_ITEM_SPAWNED,
};

#endif //SPACESHOOTER_EVENT_H